import { NextResponse } from "next/server";

export async function POST(request: Request) {
  const secret = request.headers.get("x-pipeline-secret");
  if (secret !== process.env.PIPELINE_SECRET) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  return NextResponse.json({
    message: "Reviews are generated by scheduled tasks",
  });
}
